# k Vecinos más próximos

En este archivo se desarrolla el algoritmo de **kNN** en el cual se emplean las características 'Seq', 'M', 'R', 'Teff','L','Meta','logg' y 'Prot' para estimar la edad estelar.

In [26]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors, KNeighborsRegressor
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

df = pd.read_csv('/Users/jarmireciomartinez/Doctorado_Python/Pruebas_regresion/gyro_tot_v20180801.txt', sep="\t", header=0)
df

,Seq,SIMBAD_ID,M,eM1,eM2,R,eR1,eR2,Teff,eTeff1,...,cutoff,class,type,cat1,cat2,e_M,e_R,e_Teff,e_L,mode
0,1,KIC10003270,1.416000,0.207466,0.103233,2.362000,0.114948,0.098478,6594,69,...,3.471749,MS,F,serenelli17,garcia14,10.970989,4.517914,1.046406,9.498159,Ast
1,2,KIC10016239,1.264000,0.054037,0.059641,1.298000,0.024698,0.025554,6482,51,...,3.545165,MS,F,serenelli17,garcia14,4.496741,1.935749,0.786794,8.232459,Ast
2,3,KIC10024648,1.444000,0.087693,0.137295,2.000000,0.050448,0.060208,6409,157,...,3.593017,MS,F,serenelli17,garcia14,7.790441,2.766399,2.449680,8.551756,Ast
3,4,KIC10025841,1.121000,0.133195,0.096649,1.521000,0.094557,0.085094,5738,187,...,4.032857,MS,G,serenelli17,garcia14,10.251748,5.905685,3.258975,8.542442,Ast
4,5,KIC10068307,1.608100,0.026300,0.026300,2.164600,0.013900,0.013900,6132,77,...,3.774590,MS,F,silva17,garcia14,1.635470,0.642151,1.255708,6.023016,Ast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459,1460,KIC9837012,0.886374,0.022743,0.022743,0.777651,0.055476,0.055476,5579,183,...,4.137082,MS,G,mathur17,meibom11,2.565851,7.133751,3.432515,11.812753,Clust
1460,1461,KIC9838215,0.975155,0.022871,0.022871,0.919946,0.057136,0.057136,5776,138,...,4.007948,MS,G,mathur17,meibom11,2.345409,6.210840,2.683518,10.759006,Clust
1461,1462,KIC9896609,0.762092,0.022697,0.022697,0.650313,0.050160,0.050160,5024,151,...,4.500884,MS,K,mathur17,meibom11,2.978281,7.713252,2.856290,14.843708,Clust
1462,1463,KIC9896700,1.017446,0.022739,0.022739,0.982039,0.059040,0.059040,5889,142,...,3.933877,MS,G,mathur17,meibom11,2.234908,6.011960,2.708439,10.073298,Clust
1463,1464,KIC9957187,0.983718,0.048498,0.048498,0.920374,0.116501,0.116501,5838,157,...,3.967307,MS,G,mathur17,meibom11,4.930028,12.657988,2.843440,25.266281,Clust

In [27]:
# Se eliminan las filas con valores NULL/NA
df = df.dropna()

In [28]:
df_2 = df[['Seq', 'M', 'R', 'Teff','L','Meta','logg','Prot','Age']]
df_2

     Seq       M       R  Teff        L   Meta    logg    Prot     Age
0      1  1.4160  2.3620  6594   9.8470 -0.181  3.8480   7.090  2.4670
1      2  1.2640  1.2980  6482   2.5670 -0.005  4.3120   4.910  1.2890
2      3  1.4440  2.0000  6409   5.8750 -0.006  3.9940  10.580  2.3400
3      4  1.1210  1.5210  5738   3.1810  0.197  4.1270  11.840  7.2890
4      5  1.6081  2.1646  6132   6.6910 -0.230  3.9732  18.600  2.0082
..   ...     ...     ...   ...      ...    ...     ...     ...     ...
307  308  1.2910  1.7750  6550   5.8370 -0.307  4.0480  10.340  2.8120
308  309  1.1680  2.0140  6074   5.2160 -0.314  3.8960  21.070  4.9240
309  310  1.6260  3.3990  5936  14.4300 -0.054  3.5880  15.650  1.7790
310  311  1.5300  2.7640  6000   9.8680  0.160  3.7390  17.295  2.4890
311  312  0.8830  0.8820  5434   0.6574  0.118  4.4920  34.200  7.8400

[300 rows x 9 columns]

In [29]:
#Definición de las variables a emplear

Y_knn = np.array(df_2['Age']) #Predecir Age
X_knn = np.array(df[['Seq', 'M', 'R', 'Teff','L','Meta','logg','Prot']]) #A través de las demás columnas

In [30]:
#Se separa el 20% de los datos para test

X_train, X_test, Y_train, Y_test = train_test_split(X_knn, Y_knn, test_size=0.2)

In [31]:
#Definición del algoritmo
knn_regr = KNeighborsRegressor()

#Entrenamiento del algoritmo
knn_regr.fit(X_train,Y_train)

KNeighborsRegressor()

In [32]:
#Realizar una predicción

Y_pred = knn_regr.predict(X_test)

In [37]:
#Comparación de arrays

data = {'Y_test':  Y_test,
        'Y_pred': Y_pred,
        }

df_new = pd.DataFrame (data, columns = ['Y_test','Y_pred'])

print (df_new)

    Y_test   Y_pred
0   4.0000  3.18500
1   2.5460  3.51120
2   2.1000  1.69860
3   3.8000  3.23340
4   4.8000  3.32100
5   1.6441  2.28220
6   4.1410  5.76948
7   1.8170  3.31380
8   3.6350  2.34420
9   2.8180  3.22442
10  7.2560  5.69738
11  1.7180  2.50660
12  3.0720  3.26680
13  5.1650  4.18580
14  3.8580  4.88520
15  3.0190  4.49520
16  3.0840  3.07020
17  1.5750  1.93088
18  3.1120  3.15860
19  3.3000  1.93680
20  5.2530  4.48154
21  2.4830  3.30480
22  3.5020  3.64740
23  8.2880  6.73480
24  1.8510  2.33440
25  6.9200  5.50380
26  2.3247  3.08160
27  4.9000  3.30480
28  3.6050  3.31940
29  2.8750  2.80980
30  2.4990  3.86294
31  4.4910  5.28974
32  8.7200  7.15796
33  2.4140  2.33080
34  6.2170  6.85998
35  1.3160  2.28380
36  3.7350  3.18500
37  3.3000  1.99740
38  2.2490  2.33600
39  7.7990  8.31260
40  7.2282  6.39618
41  2.4500  2.64220
42  2.7480  2.24480
43  3.1030  2.24480
44  3.1000  2.83460
45  2.3520  2.81840
46  3.1250  2.70762
47  4.0070  4.53300
48  2.1090  2.37380
49  3.6080  2.24200
50  1.8880  3.02540
51  3.8760  3.41334
52  3.9000  4.46060
53  3.0540  3.71020
54  4.7430  5.74434
55  4.7690  3.88314
56  5.4050  3.86294
57  2.7700  6.67500
58  3.7000  3.86294
59  3.4830  3.76840

In [43]:
#Precisión del algoritmo (conjunto entrenamiento)

print('Precisión del algoritmo:')
print(knn_regr.score(X_train, Y_train))

Precisión del algoritmo:
0.5741726374098147

In [44]:
#Precisión del algoritmo (conjunto test)

print('Precisión del algoritmo:')
print(knn_regr.score(X_test, Y_test))

Precisión del algoritmo:
0.6246894335055839

In [40]:
from sklearn.metrics import mean_squared_error, r2_score, max_error

# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(Y_test, Y_pred))
# The max error
print('Max error: %.2f'
      % max_error(Y_test, Y_pred))

Mean squared error: 1.08
Coefficient of determination: 0.62
Max error: 3.90

In [36]:
knn_regr_sc = knn_regr.score(X_test, Y_test)
%store knn_regr_sc

Stored 'knn_regr_sc' (float64)