# k Vecinos más próximos

En este archivo se desarrolla el algoritmo de **kNN** en el cual se emplean las características 'Seq', 'M', 'R', 'Teff','L','Meta','logg' y 'Prot' para estimar la edad estelar.

In [13]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors, KNeighborsRegressor
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

df = pd.read_csv('/Users/jarmireciomartinez/Doctorado_Python/Pruebas_regresion/gyro_tot_v20180801.txt', sep="\t", header=0)
df

,Seq,SIMBAD_ID,M,eM1,eM2,R,eR1,eR2,Teff,eTeff1,...,cutoff,class,type,cat1,cat2,e_M,e_R,e_Teff,e_L,mode
0,1,KIC10003270,1.416000,0.207466,0.103233,2.362000,0.114948,0.098478,6594,69,...,3.471749,MS,F,serenelli17,garcia14,10.970989,4.517914,1.046406,9.498159,Ast
1,2,KIC10016239,1.264000,0.054037,0.059641,1.298000,0.024698,0.025554,6482,51,...,3.545165,MS,F,serenelli17,garcia14,4.496741,1.935749,0.786794,8.232459,Ast
2,3,KIC10024648,1.444000,0.087693,0.137295,2.000000,0.050448,0.060208,6409,157,...,3.593017,MS,F,serenelli17,garcia14,7.790441,2.766399,2.449680,8.551756,Ast
3,4,KIC10025841,1.121000,0.133195,0.096649,1.521000,0.094557,0.085094,5738,187,...,4.032857,MS,G,serenelli17,garcia14,10.251748,5.905685,3.258975,8.542442,Ast
4,5,KIC10068307,1.608100,0.026300,0.026300,2.164600,0.013900,0.013900,6132,77,...,3.774590,MS,F,silva17,garcia14,1.635470,0.642151,1.255708,6.023016,Ast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459,1460,KIC9837012,0.886374,0.022743,0.022743,0.777651,0.055476,0.055476,5579,183,...,4.137082,MS,G,mathur17,meibom11,2.565851,7.133751,3.432515,11.812753,Clust
1460,1461,KIC9838215,0.975155,0.022871,0.022871,0.919946,0.057136,0.057136,5776,138,...,4.007948,MS,G,mathur17,meibom11,2.345409,6.210840,2.683518,10.759006,Clust
1461,1462,KIC9896609,0.762092,0.022697,0.022697,0.650313,0.050160,0.050160,5024,151,...,4.500884,MS,K,mathur17,meibom11,2.978281,7.713252,2.856290,14.843708,Clust
1462,1463,KIC9896700,1.017446,0.022739,0.022739,0.982039,0.059040,0.059040,5889,142,...,3.933877,MS,G,mathur17,meibom11,2.234908,6.011960,2.708439,10.073298,Clust
1463,1464,KIC9957187,0.983718,0.048498,0.048498,0.920374,0.116501,0.116501,5838,157,...,3.967307,MS,G,mathur17,meibom11,4.930028,12.657988,2.843440,25.266281,Clust

In [14]:
# Se eliminan las filas con valores NULL/NA
df = df.dropna()

In [15]:
df_2 = df[['Seq', 'M', 'R', 'Teff','L','Meta','logg','Prot','Age']]
df_2

     Seq       M       R  Teff        L   Meta    logg    Prot     Age
0      1  1.4160  2.3620  6594   9.8470 -0.181  3.8480   7.090  2.4670
1      2  1.2640  1.2980  6482   2.5670 -0.005  4.3120   4.910  1.2890
2      3  1.4440  2.0000  6409   5.8750 -0.006  3.9940  10.580  2.3400
3      4  1.1210  1.5210  5738   3.1810  0.197  4.1270  11.840  7.2890
4      5  1.6081  2.1646  6132   6.6910 -0.230  3.9732  18.600  2.0082
..   ...     ...     ...   ...      ...    ...     ...     ...     ...
307  308  1.2910  1.7750  6550   5.8370 -0.307  4.0480  10.340  2.8120
308  309  1.1680  2.0140  6074   5.2160 -0.314  3.8960  21.070  4.9240
309  310  1.6260  3.3990  5936  14.4300 -0.054  3.5880  15.650  1.7790
310  311  1.5300  2.7640  6000   9.8680  0.160  3.7390  17.295  2.4890
311  312  0.8830  0.8820  5434   0.6574  0.118  4.4920  34.200  7.8400

[300 rows x 9 columns]

In [47]:
#Definición de las variables a emplear

Y_knn = np.array(df_2['Age']) #Predecir Age
#X_knn = df_2[['M']] #A través de la masa
X_knn = np.array(df[['Seq', 'M', 'R', 'Teff','L','Meta','logg','Prot']]) #A través de las demás columnas

from sklearn import preprocessing
from sklearn.preprocessing import normalize

X_norm = preprocessing.normalize(X_knn, norm='l2') #Normalización del conjunto de características

In [48]:
#Se separa el 20% de los datos para test

X_train, X_test, Y_train, Y_test = train_test_split(X_norm, Y_knn, test_size=0.2)

In [49]:
#Definición del algoritmo
knn_regr = KNeighborsRegressor()

#Entrenamiento del algoritmo
knn_regr.fit(X_train,Y_train)

KNeighborsRegressor()

In [50]:
#Realizar una predicción

Y_pred = knn_regr.predict(X_test)

In [51]:
#Comparación de arrays

data = {'Y_test':  Y_test,
        'Y_pred': Y_pred,
        }

df_new = pd.DataFrame (data, columns = ['Y_test','Y_pred'])

print (df_new)

     Y_test   Y_pred
0    1.2890  3.10140
1    5.2530  3.06540
2    1.6740  1.75560
3    3.8000  2.51848
4    2.8180  2.88782
5    3.0840  2.86680
6    5.1740  3.96680
7    2.3260  4.03740
8    2.5460  4.66234
9    5.1000  4.04440
10   2.0082  4.25060
11   2.6490  3.94960
12   2.1210  3.14654
13   2.4350  1.89400
14   6.0920  5.90880
15   3.4260  2.87020
16   3.0360  5.68920
17   2.9030  3.44080
18   2.8770  5.08700
19   4.9000  3.71360
20   7.3000  4.27420
21   3.6660  3.99440
22   3.9210  3.05500
23   2.6420  3.16954
24   1.7790  4.15180
25   2.2610  2.68580
26   4.0270  4.59600
27   3.5020  3.93502
28   2.5710  4.04960
29   5.8360  2.74382
30   2.5110  4.95940
31   7.2282  5.57018
32  10.7000  6.48480
33   2.3250  4.39382
34   2.4930  4.00300
35   2.4140  3.56780
36   2.1300  4.07854
37   4.8370  3.29120
38   2.7480  4.04960
39   1.1590  3.12040
40   1.7300  4.48660
41   3.8420  4.77700
42   2.8090  2.76540
43   5.2560  5.33820
44   2.4990  3.19346
45   3.1030  2.73740
46   4.1310  5.89820
47   9.9670  2.74382
48   2.7480  3.08422
49   3.4830  3.25620
50   3.6400  3.56460
51   4.1820  2.96462
52   1.7260  2.66180
53   3.2090  3.47254
54   3.7780  3.11460
55   2.4830  8.79900
56   5.7927  4.04440
57   3.6080  3.02740
58   2.3000  3.68760
59   5.1150  4.98640

In [52]:
#Precisión del algoritmo (conjunto entrenamiento)

print('Precisión del algoritmo:')
print(knn_regr.score(X_train, Y_train))

Precisión del algoritmo:
0.4988073018415923

In [53]:
#Precisión del algoritmo (conjunto test)

print('Precisión del algoritmo:')
print(knn_regr.score(X_test, Y_test))

Precisión del algoritmo:
-0.11198754468160166

In [54]:
from sklearn.metrics import mean_squared_error, r2_score, max_error, mean_absolute_error

# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(Y_test, Y_pred))
# The max error
print('Max error: %.2f'
      % max_error(Y_test, Y_pred))
# The mean absolute error
print('MAE: %.2f'
      % mean_absolute_error(Y_test, Y_pred))

Mean squared error: 3.82
Coefficient of determination: -0.11
Max error: 7.22
MAE: 1.41

In [36]:
knn_regr_sc = knn_regr.score(X_test, Y_test)
%store knn_regr_sc

Stored 'knn_regr_sc' (float64)