# Regresión lineal múltiple

En este archivo se desarrolla el algoritmo de **regresión lineal múltiple** en el cual se emplean las características 'Seq', 'M', 'R', 'Teff','L','Meta','logg' y 'Prot' para estimar la edad estelar.

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

df = pd.read_csv('/Users/jarmireciomartinez/Doctorado_Python/Pruebas_regresion/gyro_tot_v20180801.txt', sep="\t", header=0)
df

,Seq,SIMBAD_ID,M,eM1,eM2,R,eR1,eR2,Teff,eTeff1,...,cutoff,class,type,cat1,cat2,e_M,e_R,e_Teff,e_L,mode
0,1,KIC10003270,1.416000,0.207466,0.103233,2.362000,0.114948,0.098478,6594,69,...,3.471749,MS,F,serenelli17,garcia14,10.970989,4.517914,1.046406,9.498159,Ast
1,2,KIC10016239,1.264000,0.054037,0.059641,1.298000,0.024698,0.025554,6482,51,...,3.545165,MS,F,serenelli17,garcia14,4.496741,1.935749,0.786794,8.232459,Ast
2,3,KIC10024648,1.444000,0.087693,0.137295,2.000000,0.050448,0.060208,6409,157,...,3.593017,MS,F,serenelli17,garcia14,7.790441,2.766399,2.449680,8.551756,Ast
3,4,KIC10025841,1.121000,0.133195,0.096649,1.521000,0.094557,0.085094,5738,187,...,4.032857,MS,G,serenelli17,garcia14,10.251748,5.905685,3.258975,8.542442,Ast
4,5,KIC10068307,1.608100,0.026300,0.026300,2.164600,0.013900,0.013900,6132,77,...,3.774590,MS,F,silva17,garcia14,1.635470,0.642151,1.255708,6.023016,Ast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459,1460,KIC9837012,0.886374,0.022743,0.022743,0.777651,0.055476,0.055476,5579,183,...,4.137082,MS,G,mathur17,meibom11,2.565851,7.133751,3.432515,11.812753,Clust
1460,1461,KIC9838215,0.975155,0.022871,0.022871,0.919946,0.057136,0.057136,5776,138,...,4.007948,MS,G,mathur17,meibom11,2.345409,6.210840,2.683518,10.759006,Clust
1461,1462,KIC9896609,0.762092,0.022697,0.022697,0.650313,0.050160,0.050160,5024,151,...,4.500884,MS,K,mathur17,meibom11,2.978281,7.713252,2.856290,14.843708,Clust
1462,1463,KIC9896700,1.017446,0.022739,0.022739,0.982039,0.059040,0.059040,5889,142,...,3.933877,MS,G,mathur17,meibom11,2.234908,6.011960,2.708439,10.073298,Clust
1463,1464,KIC9957187,0.983718,0.048498,0.048498,0.920374,0.116501,0.116501,5838,157,...,3.967307,MS,G,mathur17,meibom11,4.930028,12.657988,2.843440,25.266281,Clust

In [2]:
# Se eliminan las filas con valores NULL/NA

df = df.dropna()

In [3]:
df_2 = df[['Seq', 'M', 'R', 'Teff','L','Meta','logg','Prot','Age']]
df_2

     Seq       M       R  Teff        L   Meta    logg    Prot     Age
0      1  1.4160  2.3620  6594   9.8470 -0.181  3.8480   7.090  2.4670
1      2  1.2640  1.2980  6482   2.5670 -0.005  4.3120   4.910  1.2890
2      3  1.4440  2.0000  6409   5.8750 -0.006  3.9940  10.580  2.3400
3      4  1.1210  1.5210  5738   3.1810  0.197  4.1270  11.840  7.2890
4      5  1.6081  2.1646  6132   6.6910 -0.230  3.9732  18.600  2.0082
..   ...     ...     ...   ...      ...    ...     ...     ...     ...
307  308  1.2910  1.7750  6550   5.8370 -0.307  4.0480  10.340  2.8120
308  309  1.1680  2.0140  6074   5.2160 -0.314  3.8960  21.070  4.9240
309  310  1.6260  3.3990  5936  14.4300 -0.054  3.5880  15.650  1.7790
310  311  1.5300  2.7640  6000   9.8680  0.160  3.7390  17.295  2.4890
311  312  0.8830  0.8820  5434   0.6574  0.118  4.4920  34.200  7.8400

[300 rows x 9 columns]

In [14]:
#Definición de las variables a emplear

Y_mult = np.array(df_2['Age']) #Predecir Age
X_mult = np.array(df[['Seq', 'M', 'R', 'Teff','L','Meta','logg','Prot']]) #A través de las demás columnas

from sklearn import preprocessing
from sklearn.preprocessing import normalize

X_norm = preprocessing.normalize(X_mult, norm='l2') #Normalización del conjunto de características

In [15]:
#Se separa el 20% de los datos para test

X_train, X_test, Y_train, Y_test = train_test_split(X_mult, Y_mult, test_size=0.2)

In [16]:
#Definición del algoritmo
regr_mult = linear_model.LinearRegression()

#Entrenamiento del algoritmo
regr_mult.fit(X_train,Y_train)

LinearRegression()

In [17]:
#Realizar una predicción
Y_pred = regr_mult.predict(X_test)

In [18]:
#Comparación de arrays

data = {'Y_test':  Y_test,
        'Y_pred': Y_pred,
        }

df_new = pd.DataFrame (data, columns = ['Y_test','Y_pred'])

print (df_new)

    Y_test    Y_pred
0   3.4330  4.052277
1   5.2560  5.425208
2   4.8230  5.071550
3   1.1590  3.785907
4   7.5890  7.453695
5   5.5000  5.033308
6   1.7407  4.386816
7   1.6740  2.059624
8   2.2000  0.544358
9   2.6420  3.823437
10  4.0000  3.575429
11  3.6350  3.553206
12  1.9000  2.196193
13  1.7264  1.694571
14  2.7420  2.608089
15  3.3000  2.389483
16  3.1000  2.564407
17  3.4000  3.171044
18  5.3940  6.180149
19  5.6270  5.126688
20  2.4261  2.099576
21  1.5520  0.974427
22  2.3247  1.845187
23  6.3000  7.674916
24  2.5830  2.614947
25  1.9241  1.318166
26  4.5300  6.023495
27  3.4240  3.774023
28  0.4840  0.350501
29  2.7000  1.007333
30  3.7350  4.596304
31  2.1300  1.891088
32  9.9670  8.196735
33  4.9190  4.666355
34  4.4910  5.422756
35  1.9000  5.244470
36  2.8040  2.896209
37  4.1820  4.469211
38  3.4000  6.220281
39  3.2090  3.545452
40  5.1740  5.402008
41  6.0340  5.713878
42  7.8400  8.148833
43  5.2980  5.468447
44  3.9000  3.116094
45  3.7000  3.208121
46  5.4140  5.143349
47  3.6840  4.321023
48  3.4830  3.737891
49  7.2890  6.768769
50  2.4740  2.664286
51  2.1210  1.486907
52  2.3250  3.293578
53  7.8800  6.836971
54  3.9000  3.418302
55  3.5020  3.740759
56  3.0190  4.088524
57  2.4500  2.768990
58  2.9030  3.602792
59  5.5480  5.166525

In [19]:
#Valores de pendiente e intersección

print('Valor de la pendiente:')
print(regr_mult.coef_)
print('Valor de la intersección:')
print(regr_mult.intercept_)

Valor de la pendiente:
[ 6.41804637e-05 -6.92698986e+00 -5.57590592e+00 -3.00017813e-03
  3.68683714e-01  1.14594110e+00 -1.03697032e+01  1.90050196e-03]
Valor de la intersección:
81.60437303454228

In [20]:
#Precisión del algoritmo (conjunto entrenamiento)
print('Precisión del algoritmo:')
print(regr_mult.score(X_train, Y_train))

Precisión del algoritmo:
0.7946964488208474

In [21]:
#Precisión del algoritmo (conjunto test)
print('Precisión del algoritmo:')
print(regr_mult.score(X_test, Y_test))

Precisión del algoritmo:
0.7096187431788705

In [22]:
from sklearn.metrics import mean_squared_error, r2_score, max_error, mean_absolute_error

# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(Y_test, Y_pred))
# The max error
print('Max error: %.2f'
      % max_error(Y_test, Y_pred))
# The mean absolute error
print('MAE: %.2f'
      % mean_absolute_error(Y_test, Y_pred))

Mean squared error: 1.00
Coefficient of determination: 0.71
Max error: 3.34
MAE: 0.70

In [52]:
#Almacenar valor

lineal_mult = regr_mult.score(X_test, Y_test)
%store lineal_mult

Stored 'lineal_mult' (float64)