# Descenso de Gradiente Estocástico

En este archivo se desarrolla el algoritmo de **SGD** en el cual se emplean las características 'Seq', 'M', 'R', 'Teff','L','Meta','logg' y 'Prot' para estimar la edad estelar.

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

df = pd.read_csv('/Users/jarmireciomartinez/Doctorado_Python/Pruebas_regresion/gyro_tot_v20180801.txt', sep="\t", header=0)
df

,Seq,SIMBAD_ID,M,eM1,eM2,R,eR1,eR2,Teff,eTeff1,...,cutoff,class,type,cat1,cat2,e_M,e_R,e_Teff,e_L,mode
0,1,KIC10003270,1.416000,0.207466,0.103233,2.362000,0.114948,0.098478,6594,69,...,3.471749,MS,F,serenelli17,garcia14,10.970989,4.517914,1.046406,9.498159,Ast
1,2,KIC10016239,1.264000,0.054037,0.059641,1.298000,0.024698,0.025554,6482,51,...,3.545165,MS,F,serenelli17,garcia14,4.496741,1.935749,0.786794,8.232459,Ast
2,3,KIC10024648,1.444000,0.087693,0.137295,2.000000,0.050448,0.060208,6409,157,...,3.593017,MS,F,serenelli17,garcia14,7.790441,2.766399,2.449680,8.551756,Ast
3,4,KIC10025841,1.121000,0.133195,0.096649,1.521000,0.094557,0.085094,5738,187,...,4.032857,MS,G,serenelli17,garcia14,10.251748,5.905685,3.258975,8.542442,Ast
4,5,KIC10068307,1.608100,0.026300,0.026300,2.164600,0.013900,0.013900,6132,77,...,3.774590,MS,F,silva17,garcia14,1.635470,0.642151,1.255708,6.023016,Ast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459,1460,KIC9837012,0.886374,0.022743,0.022743,0.777651,0.055476,0.055476,5579,183,...,4.137082,MS,G,mathur17,meibom11,2.565851,7.133751,3.432515,11.812753,Clust
1460,1461,KIC9838215,0.975155,0.022871,0.022871,0.919946,0.057136,0.057136,5776,138,...,4.007948,MS,G,mathur17,meibom11,2.345409,6.210840,2.683518,10.759006,Clust
1461,1462,KIC9896609,0.762092,0.022697,0.022697,0.650313,0.050160,0.050160,5024,151,...,4.500884,MS,K,mathur17,meibom11,2.978281,7.713252,2.856290,14.843708,Clust
1462,1463,KIC9896700,1.017446,0.022739,0.022739,0.982039,0.059040,0.059040,5889,142,...,3.933877,MS,G,mathur17,meibom11,2.234908,6.011960,2.708439,10.073298,Clust
1463,1464,KIC9957187,0.983718,0.048498,0.048498,0.920374,0.116501,0.116501,5838,157,...,3.967307,MS,G,mathur17,meibom11,4.930028,12.657988,2.843440,25.266281,Clust

In [2]:
# Se eliminan las filas con valores NULL/NA

df = df.dropna()

In [3]:
df_2 = df[['Seq', 'M', 'R', 'Teff','L','Meta','logg','Prot','Age']]
df_2

     Seq       M       R  Teff        L   Meta    logg    Prot     Age
0      1  1.4160  2.3620  6594   9.8470 -0.181  3.8480   7.090  2.4670
1      2  1.2640  1.2980  6482   2.5670 -0.005  4.3120   4.910  1.2890
2      3  1.4440  2.0000  6409   5.8750 -0.006  3.9940  10.580  2.3400
3      4  1.1210  1.5210  5738   3.1810  0.197  4.1270  11.840  7.2890
4      5  1.6081  2.1646  6132   6.6910 -0.230  3.9732  18.600  2.0082
..   ...     ...     ...   ...      ...    ...     ...     ...     ...
307  308  1.2910  1.7750  6550   5.8370 -0.307  4.0480  10.340  2.8120
308  309  1.1680  2.0140  6074   5.2160 -0.314  3.8960  21.070  4.9240
309  310  1.6260  3.3990  5936  14.4300 -0.054  3.5880  15.650  1.7790
310  311  1.5300  2.7640  6000   9.8680  0.160  3.7390  17.295  2.4890
311  312  0.8830  0.8820  5434   0.6574  0.118  4.4920  34.200  7.8400

[300 rows x 9 columns]

In [28]:
#Definición de las variables a emplear

Y_sgd = np.array(df_2['Age']) #Predecir Age
#X_sgd = np.array(df[['Seq', 'M', 'R', 'Teff','L','Meta','logg','Prot']]) #A través de las demás columnas
X_sgd = np.array(df_2[['M']]) #A través de la masa

from sklearn import preprocessing
from sklearn.preprocessing import normalize

X_norm = preprocessing.normalize(X_sgd, norm='l2') #Normalización del conjunto de características

In [29]:
#Se separa el 20% de los datos para test

X_train, X_test, Y_train, Y_test = train_test_split(X_sgd, Y_sgd, test_size=0.2)

In [30]:
#Definición del algoritmo
sgd_regr = SGDRegressor()

#Entrenamiento del algoritmo
sgd_regr.fit(X_train,Y_train)

SGDRegressor()

In [31]:
#Realizar una predicción

Y_pred = sgd_regr.predict(X_test)

In [32]:
#Comparación de arrays

data = {'Y_test':  Y_test,
        'Y_pred': Y_pred,
        }

df_new = pd.DataFrame (data, columns = ['Y_test','Y_pred'])

print (df_new)

     Y_test    Y_pred
0    2.6050  3.506391
1    5.1390  4.256754
2    3.3000  3.157573
3    4.8370  4.122906
4    2.8770  4.082345
5    3.6000  3.847096
6   10.3904  5.910799
7    6.9070  4.487947
8    5.4050  4.414939
9    4.8230  4.045841
10   2.5790  3.834928
11   2.8750  3.595623
12   5.6040  4.147242
13   1.5000  4.329763
14   4.9000  3.563175
15   2.5830  3.177853
16   6.3440  4.382491
17  13.6200  5.757482
18  12.4000  4.982782
19   1.5520  2.180072
20   1.9550  2.610010
21   4.1820  3.745696
22   2.1300  2.861483
23   3.4330  3.433382
24   5.1740  4.260810
25   2.5110  3.161629
26   6.2170  4.341931
27   1.7407  4.410883
28   3.6000  3.684855
29   2.7600  3.340094
30   3.7350  3.644295
31   1.2940  1.433764
32   4.7430  4.244586
33   2.6420  3.368486
34   3.3340  4.366267
35   3.4000  3.360374
36   3.9000  3.400934
37   4.1240  4.037729
38   8.2880  4.540676
39   5.2980  4.090458
40   4.9120  4.573124
41   2.7480  3.684855
42   1.9000  3.117013
43   2.2610  3.044004
44   1.9000  3.684855
45   4.3800  3.948497
46   5.4140  4.256754
47   3.1310  4.370323
48   3.9000  3.319814
49   2.2180  2.719523
50   4.4990  4.195914
51   3.6050  4.090458
52   1.7790  2.362593
53   4.9190  4.131018
54   6.0340  4.447387
55   6.3000  4.212138
56   3.8420  3.425270
57   3.4000  3.035892
58   2.3520  3.461774
59   1.7180  3.729472

In [33]:
#Precisión del algoritmo (conjunto entrenamiento)

print('Precisión del algoritmo:')
print(sgd_regr.score(X_train, Y_train))

Precisión del algoritmo:
0.3734629930704241

In [34]:
#Precisión del algoritmo (conjunto test)

print('Precisión del algoritmo:')
print(sgd_regr.score(X_test, Y_test))

Precisión del algoritmo:
0.3568957072764388

In [35]:
from sklearn.metrics import mean_squared_error, r2_score, max_error, mean_absolute_error

# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(Y_test, Y_pred))
# The max error
print('Max error: %.2f'
      % max_error(Y_test, Y_pred))
# The mean absolute error
print('MAE: %.2f'
      % mean_absolute_error(Y_test, Y_pred))

Mean squared error: 3.69
Coefficient of determination: 0.36
Max error: 7.86
MAE: 1.24

In [25]:
sgd_regr_sc = sgd_regr.score(X_test, Y_test)
%store sgd_regr_sc

Stored 'sgd_regr_sc' (float64)