# Descenso de Gradiente Estocástico

En este archivo se desarrolla el algoritmo de **SGD** en el cual se emplean las características 'Seq', 'M', 'R', 'Teff','L','Meta','logg' y 'Prot' para estimar la edad estelar.

In [14]:
import pandas as pd
import numpy as np
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

df = pd.read_csv('/Users/jarmireciomartinez/Doctorado_Python/Pruebas_regresion/gyro_tot_v20180801.txt', sep="\t", header=0)
df

,Seq,SIMBAD_ID,M,eM1,eM2,R,eR1,eR2,Teff,eTeff1,...,cutoff,class,type,cat1,cat2,e_M,e_R,e_Teff,e_L,mode
0,1,KIC10003270,1.416000,0.207466,0.103233,2.362000,0.114948,0.098478,6594,69,...,3.471749,MS,F,serenelli17,garcia14,10.970989,4.517914,1.046406,9.498159,Ast
1,2,KIC10016239,1.264000,0.054037,0.059641,1.298000,0.024698,0.025554,6482,51,...,3.545165,MS,F,serenelli17,garcia14,4.496741,1.935749,0.786794,8.232459,Ast
2,3,KIC10024648,1.444000,0.087693,0.137295,2.000000,0.050448,0.060208,6409,157,...,3.593017,MS,F,serenelli17,garcia14,7.790441,2.766399,2.449680,8.551756,Ast
3,4,KIC10025841,1.121000,0.133195,0.096649,1.521000,0.094557,0.085094,5738,187,...,4.032857,MS,G,serenelli17,garcia14,10.251748,5.905685,3.258975,8.542442,Ast
4,5,KIC10068307,1.608100,0.026300,0.026300,2.164600,0.013900,0.013900,6132,77,...,3.774590,MS,F,silva17,garcia14,1.635470,0.642151,1.255708,6.023016,Ast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459,1460,KIC9837012,0.886374,0.022743,0.022743,0.777651,0.055476,0.055476,5579,183,...,4.137082,MS,G,mathur17,meibom11,2.565851,7.133751,3.432515,11.812753,Clust
1460,1461,KIC9838215,0.975155,0.022871,0.022871,0.919946,0.057136,0.057136,5776,138,...,4.007948,MS,G,mathur17,meibom11,2.345409,6.210840,2.683518,10.759006,Clust
1461,1462,KIC9896609,0.762092,0.022697,0.022697,0.650313,0.050160,0.050160,5024,151,...,4.500884,MS,K,mathur17,meibom11,2.978281,7.713252,2.856290,14.843708,Clust
1462,1463,KIC9896700,1.017446,0.022739,0.022739,0.982039,0.059040,0.059040,5889,142,...,3.933877,MS,G,mathur17,meibom11,2.234908,6.011960,2.708439,10.073298,Clust
1463,1464,KIC9957187,0.983718,0.048498,0.048498,0.920374,0.116501,0.116501,5838,157,...,3.967307,MS,G,mathur17,meibom11,4.930028,12.657988,2.843440,25.266281,Clust

In [15]:
# Se eliminan las filas con valores NULL/NA

df = df.dropna()

In [16]:
df_2 = df[['Seq', 'M', 'R', 'Teff','L','Meta','logg','Prot','Age']]
df_2

     Seq       M       R  Teff        L   Meta    logg    Prot     Age
0      1  1.4160  2.3620  6594   9.8470 -0.181  3.8480   7.090  2.4670
1      2  1.2640  1.2980  6482   2.5670 -0.005  4.3120   4.910  1.2890
2      3  1.4440  2.0000  6409   5.8750 -0.006  3.9940  10.580  2.3400
3      4  1.1210  1.5210  5738   3.1810  0.197  4.1270  11.840  7.2890
4      5  1.6081  2.1646  6132   6.6910 -0.230  3.9732  18.600  2.0082
..   ...     ...     ...   ...      ...    ...     ...     ...     ...
307  308  1.2910  1.7750  6550   5.8370 -0.307  4.0480  10.340  2.8120
308  309  1.1680  2.0140  6074   5.2160 -0.314  3.8960  21.070  4.9240
309  310  1.6260  3.3990  5936  14.4300 -0.054  3.5880  15.650  1.7790
310  311  1.5300  2.7640  6000   9.8680  0.160  3.7390  17.295  2.4890
311  312  0.8830  0.8820  5434   0.6574  0.118  4.4920  34.200  7.8400

[300 rows x 9 columns]

In [17]:
#Definición de las variables a emplear

Y_sgd = np.array(df_2['Age']) #Predecir Age
#X_sgd = np.array(df[['Seq', 'M', 'R', 'Teff','L','Meta','logg','Prot']]) #A través de las demás columnas
X_sgd = np.array(df_2[['M']]) #A través de la masa

In [18]:
#Se separa el 20% de los datos para test

X_train, X_test, Y_train, Y_test = train_test_split(X_sgd, Y_sgd, test_size=0.2)

In [19]:
#Definición del algoritmo
sgd_regr = SGDRegressor()

#Entrenamiento del algoritmo
sgd_regr.fit(X_train,Y_train)

SGDRegressor()

In [20]:
#Realizar una predicción

Y_pred = sgd_regr.predict(X_test)

In [21]:
#Comparación de arrays

data = {'Y_test':  Y_test,
        'Y_pred': Y_pred,
        }

df_new = pd.DataFrame (data, columns = ['Y_test','Y_pred'])

print (df_new)

    Y_test    Y_pred
0   1.6960  2.723455
1   2.8000  3.972614
2   1.9241  2.525671
3   5.7927  4.639327
4   1.9550  2.510305
5   1.0000  3.476916
6   3.8000  3.576055
7   1.6060  3.833818
8   4.1196  4.470294
9   2.8040  3.462045
10  2.4500  3.749550
11  7.8800  4.939224
12  2.4890  2.683799
13  0.8050  4.012269
14  2.7880  3.556227
15  5.1740  4.527795
16  1.7260  4.126280
17  2.1650  2.644143
18  2.8080  3.437260
19  3.3980  3.749550
20  0.4000  4.071753
21  4.0270  4.349344
22  1.9000  3.823904
23  4.5300  5.003665
24  3.4000  3.427346
25  2.6240  4.012269
26  3.4000  3.030788
27  2.8090  3.630582
28  4.9120  4.909483
29  5.4140  4.522838
30  2.3250  4.131237
31  3.8000  3.328206
32  2.8000  3.179497
33  5.8360  4.532752
34  7.3000  4.964009
35  5.1150  4.740945
36  9.9670  4.968966
37  4.0070  4.215506
38  3.0540  3.962700
39  8.7200  4.825214
40  5.0960  4.220463
41  3.3020  3.635539
42  3.1310  4.661634
43  5.5000  4.617021
44  1.1590  4.567451
45  2.4090  3.695023
46  4.2910  3.789205
47  5.1000  4.309688
48  8.6850  4.929310
49  1.7180  3.878431
50  3.0980  3.457088
51  2.8280  3.645453
52  3.0410  3.581012
53  5.1740  5.276299
54  3.6080  4.066796
55  2.5790  4.007312
56  1.8700  3.010960
57  4.8230  4.265075
58  1.3740  4.522838
59  1.5660  4.279946

In [22]:
#Precisión del algoritmo (conjunto entrenamiento)

print('Precisión del algoritmo:')
print(sgd_regr.score(X_train, Y_train))

Precisión del algoritmo:
0.46364764133151737

In [23]:
#Precisión del algoritmo (conjunto test)

print('Precisión del algoritmo:')
print(sgd_regr.score(X_test, Y_test))

Precisión del algoritmo:
0.26351070784600994

In [24]:
from sklearn.metrics import mean_squared_error, r2_score, max_error

# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(Y_test, Y_pred))
# The max error
print('Max error: %.2f'
      % max_error(Y_test, Y_pred))

Mean squared error: 2.94
Coefficient of determination: 0.26
Max error: 5.00

In [25]:
sgd_regr_sc = sgd_regr.score(X_test, Y_test)
%store sgd_regr_sc

Stored 'sgd_regr_sc' (float64)