# Árboles de decisión

En este archivo se desarrolla el algoritmo de **árboles de decisión** en el cual se emplean las características 'Seq', 'M', 'R', 'Teff','L','Meta','logg' y 'Prot' para estimar la edad estelar.

In [2]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

df = pd.read_csv('/Users/jarmireciomartinez/Doctorado_Python/Pruebas_regresion/gyro_tot_v20180801.txt', sep="\t", header=0)
df

,Seq,SIMBAD_ID,M,eM1,eM2,R,eR1,eR2,Teff,eTeff1,...,cutoff,class,type,cat1,cat2,e_M,e_R,e_Teff,e_L,mode
0,1,KIC10003270,1.416000,0.207466,0.103233,2.362000,0.114948,0.098478,6594,69,...,3.471749,MS,F,serenelli17,garcia14,10.970989,4.517914,1.046406,9.498159,Ast
1,2,KIC10016239,1.264000,0.054037,0.059641,1.298000,0.024698,0.025554,6482,51,...,3.545165,MS,F,serenelli17,garcia14,4.496741,1.935749,0.786794,8.232459,Ast
2,3,KIC10024648,1.444000,0.087693,0.137295,2.000000,0.050448,0.060208,6409,157,...,3.593017,MS,F,serenelli17,garcia14,7.790441,2.766399,2.449680,8.551756,Ast
3,4,KIC10025841,1.121000,0.133195,0.096649,1.521000,0.094557,0.085094,5738,187,...,4.032857,MS,G,serenelli17,garcia14,10.251748,5.905685,3.258975,8.542442,Ast
4,5,KIC10068307,1.608100,0.026300,0.026300,2.164600,0.013900,0.013900,6132,77,...,3.774590,MS,F,silva17,garcia14,1.635470,0.642151,1.255708,6.023016,Ast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459,1460,KIC9837012,0.886374,0.022743,0.022743,0.777651,0.055476,0.055476,5579,183,...,4.137082,MS,G,mathur17,meibom11,2.565851,7.133751,3.432515,11.812753,Clust
1460,1461,KIC9838215,0.975155,0.022871,0.022871,0.919946,0.057136,0.057136,5776,138,...,4.007948,MS,G,mathur17,meibom11,2.345409,6.210840,2.683518,10.759006,Clust
1461,1462,KIC9896609,0.762092,0.022697,0.022697,0.650313,0.050160,0.050160,5024,151,...,4.500884,MS,K,mathur17,meibom11,2.978281,7.713252,2.856290,14.843708,Clust
1462,1463,KIC9896700,1.017446,0.022739,0.022739,0.982039,0.059040,0.059040,5889,142,...,3.933877,MS,G,mathur17,meibom11,2.234908,6.011960,2.708439,10.073298,Clust
1463,1464,KIC9957187,0.983718,0.048498,0.048498,0.920374,0.116501,0.116501,5838,157,...,3.967307,MS,G,mathur17,meibom11,4.930028,12.657988,2.843440,25.266281,Clust

In [3]:
# Se eliminan las filas con valores NULL/NA
df = df.dropna()

In [4]:
df_2 = df[['Seq', 'M', 'R', 'Teff','L','Meta','logg','Prot','Age']]
df_2

     Seq       M       R  Teff        L   Meta    logg    Prot     Age
0      1  1.4160  2.3620  6594   9.8470 -0.181  3.8480   7.090  2.4670
1      2  1.2640  1.2980  6482   2.5670 -0.005  4.3120   4.910  1.2890
2      3  1.4440  2.0000  6409   5.8750 -0.006  3.9940  10.580  2.3400
3      4  1.1210  1.5210  5738   3.1810  0.197  4.1270  11.840  7.2890
4      5  1.6081  2.1646  6132   6.6910 -0.230  3.9732  18.600  2.0082
..   ...     ...     ...   ...      ...    ...     ...     ...     ...
307  308  1.2910  1.7750  6550   5.8370 -0.307  4.0480  10.340  2.8120
308  309  1.1680  2.0140  6074   5.2160 -0.314  3.8960  21.070  4.9240
309  310  1.6260  3.3990  5936  14.4300 -0.054  3.5880  15.650  1.7790
310  311  1.5300  2.7640  6000   9.8680  0.160  3.7390  17.295  2.4890
311  312  0.8830  0.8820  5434   0.6574  0.118  4.4920  34.200  7.8400

[300 rows x 9 columns]

In [23]:
#Definición de las variables a emplear
Y_tree = np.array(df_2['Age']) #Predecir Age
X_tree = df_2[['M']] #A través de la masa
#X_tree = np.array(df[['Seq', 'M', 'R', 'Teff','L','Meta','logg','Prot']]) #A través de las demás columnas

from sklearn import preprocessing
from sklearn.preprocessing import normalize

X_norm = preprocessing.normalize(X_tree, norm='l2') #Normalización del conjunto de características

In [24]:
#Se separa el 20% de los datos para test
X_train, X_test, Y_train, Y_test = train_test_split(X_tree, Y_tree, test_size=0.2)

In [25]:
#Definición del algoritmo
tree_regr = DecisionTreeRegressor()

#Entrenamiento del algoritmo
tree_regr.fit(X_train,Y_train)

DecisionTreeRegressor()

In [26]:
#Realizar una predicción
Y_pred = tree_regr.predict(X_test)

In [27]:
#Comparación de arrays

data = {'Y_test':  Y_test,
        'Y_pred': Y_pred,
        }

df_new = pd.DataFrame (data, columns = ['Y_test','Y_pred'])

print (df_new)

    Y_test   Y_pred
0   3.6000  0.80500
1   1.7790  2.00820
2   2.3260  1.99300
3   2.1210  1.81700
4   2.8280  3.30200
5   4.2910  3.19400
6   1.9660  4.74000
7   1.5750  3.45000
8   3.0030  5.20000
9   4.4990  6.27000
10  1.6740  3.68400
11  1.6573  3.05200
12  7.2890  4.33035
13  2.7420  3.80000
14  3.2090  3.77800
15  3.7350  3.19400
16  3.6660  2.53100
17  2.6240  0.80500
18  6.3000  5.17650
19  1.2360  1.31600
20  1.9210  2.60000
21  5.2000  1.15900
22  1.8290  2.10000
23  6.9070  6.50000
24  2.1000  1.92410
25  3.8000  3.10000
26  2.5710  2.79000
27  4.0320  2.81200
28  7.1000  1.15900
29  3.1000  1.81700
30  2.5790  0.80500
31  2.7600  3.05200
32  2.4930  2.10900
33  2.4890  1.69600
34  3.1120  1.60600
35  4.3000  5.17650
36  3.0410  3.10000
37  2.4740  2.79000
38  8.3810  4.53000
39  5.8840  4.90000
40  2.1920  2.96900
41  4.1820  1.88800
42  2.4500  3.39800
43  5.5000  5.50000
44  2.7460  2.87500
45  3.6000  2.32400
46  4.7220  6.72000
47  7.2560  8.72000
48  2.4830  2.06900
49  3.7000  1.50000
50  2.6490  2.32400
51  8.2880  4.80000
52  1.9000  5.54800
53  2.4990  2.06900
54  1.9000  3.06800
55  2.1650  2.21800
56  1.7270  2.00820
57  5.3940  5.56100
58  5.1000  4.82300
59  3.6080  3.77800

In [28]:
#Precisión del algoritmo (train)
print('Precisión del algoritmo:')
print(tree_regr.score(X_train, Y_train))

Precisión del algoritmo:
0.917827282678564

In [29]:
#Precisión del algoritmo (test)
print('Precisión del algoritmo:')
print(tree_regr.score(X_test, Y_test))

Precisión del algoritmo:
0.052006812631795185

In [30]:
from sklearn.metrics import mean_squared_error, r2_score, max_error, mean_absolute_error

# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(Y_test, Y_pred))
# The max error
print('Max error: %.2f'
      % max_error(Y_test, Y_pred))
# The mean absolute error
print('MAE: %.2f'
      % mean_absolute_error(Y_test, Y_pred))

Mean squared error: 2.95
Coefficient of determination: 0.05
Max error: 5.94
MAE: 1.23

In [26]:
tree_regr_sc = tree_regr.score(X_test, Y_test)
%store tree_regr_sc

Stored 'tree_regr_sc' (float64)